# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obx < Formula
  desc "A CLI for your Oblax projects"
  homepage "oblax.io"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metoant/homebrew-obx/releases/download/v0.0.2/obx_0.0.2_darwin_amd64.tar.gz"
      sha256 "45bdee17d68cb2abfc0fbbc069585aa725ba7b092dde4452ed5511817a835baa"

      def install
        bin.install "obx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metoant/homebrew-obx/releases/download/v0.0.2/obx_0.0.2_darwin_arm64.tar.gz"
      sha256 "19d16236a597a848408c789fb925ed4813a268a1a14ce4e8c4d95a0d841057eb"

      def install
        bin.install "obx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metoant/homebrew-obx/releases/download/v0.0.2/obx_0.0.2_linux_amd64.tar.gz"
        sha256 "8882800599f980171f1f5a587e07153ae2f79576a0e87e10a9b8481f9f9ef870"

        def install
          bin.install "obx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/metoant/homebrew-obx/releases/download/v0.0.2/obx_0.0.2_linux_arm64.tar.gz"
        sha256 "cdbc6102ce9f69d9648446de07ba3461751681b9701a8ff14a0e1bd67cdfd61e"

        def install
          bin.install "obx"
        end
      end
    end
  end
end
